apiVersion: v2
name: telegraf
description: Telegraf 是一个用于收集和发送指标与数据的代理，它可以集成多种数据源，是物联网数据采集的理想选择。
version: 1.0.0
appVersion: 1.29.1
home: https://www.influxdata.com/time-series-platform/telegraf/
sources:
  - https://github.com/influxdata/telegraf
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: monitoring
  yunna.net/category-zh: 监控工具
keywords:
  - metrics
  - monitoring
  - collection
  - iot
icon: https://assets.yunna.net/i/2024/12/22/vq09ht.png
