apiVersion: v2
name: mysql-adminer
description: MySQL数据库及其Web管理界面(Adminer)二合一部署方案 - 带可视化web界面
version: 0.1.0
appVersion: latest
home: https://hub.docker.com/_/adminer/
sources:
  - https://github.com/vrana/adminer/
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: database
  yunna.net/category-zh: 数据库
keywords:
  - mysql
  - database
  - web-ui
icon: https://assets.yunna.net/i/2024/12/21/114apom.png
