replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: library/adminer
  tag: latest
  pullPolicy: IfNotPresent
services:
  - name: web
    port: 8080
    targetPort: "8080"
    protocol: TCP
  - name: mysql
    port: 3306
    targetPort: "3306"
    protocol: TCP
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
  mountPath: /app/data
env:
  env1:
    name: ADMINER_DEFAULT_SERVER
    value: localhost
  env2:
    name: MYSQL_ROOT_PASSWORD
    value: admin123
  env3:
    name: MYSQL_DATABASE
    value: mydb
  env4:
    name: MYSQL_USER
    value: admin
  env5:
    name: MYSQL_PASSWORD
    value: password123
