apiVersion: v2
name: ubuntu-ssh
description: |
  一个带有 SSH 服务和常用工具的 Ubuntu 镜像应用。
version: 0.1.0
appVersion: "latest"
home: https://hub.docker.com/repository/docker/nidexiong/ubuntu-ssh
sources:
  - 无
maintainers:
  - name: "niehaoran"
    email: "niehaoran@yunna.net"
annotations:
  "yunna.net/category": "system-tools"
  "yunna.net/category-zh": "系统工具"
keywords:
  - ubuntu
  - ssh
  - tools
icon: "https://assets.yunna.net/i/2024/12/13/114s1hr.png"
