replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: ubuntu/ssh-tools
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 22

resources:
  limits:
    cpu: "1000m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "512Mi"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: "local"

env:
  env1:
    name: TZ
    value: Asia/Shanghai
  env2:
    name: LANG
    value: en_US.UTF-8
