# 全局配置
global:
  ubuntuVersion: "22.04"  # 支持 20.04, 22.04, 23.04

replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: ubuntu
  tag: ""  # tag 会根据 global.ubuntuVersion 自动设置
  pullPolicy: IfNotPresent

env:
  env1:
    name: ROOT_PASSWORD
    value: "changeme"  # 默认 root 用户密码
  env2:
    name: SSH_PORT
    value: "22"  # 默认 SSH 服务端口
  env3:
    name: PERMIT_ROOT_LOGIN
    value: "true"  # 是否允许 root 登录

# 基础工具配置
basePackages:
  - vim
  - curl
  - wget
  - net-tools
  - iputils-ping
  - telnet

service:
  type: ClusterIP  # Service 类型，默认集群内访问
  port: 22  # SSH 服务端口

# 安全配置
securityContext:
  privileged: false
  capabilities:
    add:
      - NET_ADMIN
      - SYS_ADMIN

resources:
  limits:
    cpu: 2000m
    memory: 2000Mi
  requests:
    cpu: 1000m
    memory: 1000Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "local"
  
# 高级配置
advanced:
  sshConfig:
    MaxAuthTries: 6
    ClientAliveInterval: 300
  extraPackages:
    - htop
    - nano
