replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: nidexiong/ubuntu-ssh
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 22

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: "local"
