image:
  imageRegistry: "registry-2.yunna.net"
  repository: nidexiong/ubuntu-ssh
  tag: "20.04" # 默认值为 Ubuntu 20.04
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 22

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "local"