image:
  imageRegistry: "registry-2.yunna.net"
  repository: nidexiong/ubuntu-ssh
  tag: "latest"
  pullPolicy: IfNotPresent
  ubuntuVersion: "latest" # 默认值，可以选择 "20.04" 或 "22.04"

service:
  type: ClusterIP
  port: 22

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "local"