apiVersion: v2
name: rustdesk
description: RustDesk - 开源的远程桌面软件
version: 1.0.0
appVersion: 1.1.9
home: https://rustdesk.com
sources:
  - https://github.com/rustdesk/rustdesk
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: tool
  yunna.net/category-zh: 工具
keywords:
  - Remote Desktop
  - 远程桌面
icon: https://assets.yunna.net/i/2024/12/26/3bcvu.png
