apiVersion: v2
name: netmaker
description: 创建和管理WireGuard VPN网络的平台
version: 1.0.0
appVersion: latest
home: https://netmaker.org
sources:
  - https://github.com/gravitl/netmaker
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: network
  yunna.net/category-zh: 网络工具
keywords:
  - vpn
  - wireguard
  - Self-hosted
icon: https://assets.yunna.net/i/2024/12/26/126fbbq.jpg
