apiVersion: v2
name: netmaker
description: 一个用于构建和管理虚拟网络的平台，支持零信任架构
version: 1.0.0
appVersion: latest
home: https://netmaker.org/
sources:
  - https://github.com/gravitl/netmaker
maintainers:
  - name: Gravitl
    email: info@gravitl.com
annotations:
  yunna.net/category: network
  yunna.net/category-zh: 网络
keywords:
  - VPN
  - network
  - wireguard
  - Self-hosted
icon: https://assets.yunna.net/i/2024/12/15/ci9paz.png
