replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: gravitl/netmaker
  tag: latest
  pullPolicy: IfNotPresent
services:
  - name: ui
    port: 8082
    targetPort: "8082"
    protocol: TCP
    comment: Web界面服务端口
  - name: api
    port: 8081
    targetPort: "8081"
    protocol: TCP
    comment: API服务端口
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
env:
  env1:
    name: MASTER_KEY
    value: secretkey
  env2:
    name: SERVER_HOST
    value: 0.0.0.0
  env3:
    name: NETMAKER_BASE_DOMAIN
    value: 0.0.0.0
  env4:
    name: CORS_ALLOWED_ORIGIN
    value: "*"
  env5:
    name: MQ_HOST
    value: emqx-broker
  env6:
    name: MQ_PORT
    value: "1883"
