apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ubuntu-ssh.fullname" . }}-config
  labels:
    {{- include "ubuntu-ssh.labels" . | nindent 4 }}
data:
  setup.sh: |
    #!/bin/bash
    set -e  # 捕获错误并退出

    echo "Starting SSH setup..."

    # 更新源
    echo "Updating apt package sources..."
    apt-get update || { echo "ERROR: apt-get update failed"; exit 1; }

    # 安装基础工具和 SSH 服务
    echo "Installing openssh-server and required packages..."
    apt-get install -y openssh-server {{ join " " .Values.basePackages }} {{- if .Values.advanced.extraPackages }} {{ join " " .Values.advanced.extraPackages }} {{- end }} || { echo "ERROR: apt-get install failed"; exit 1; }

    # 配置 SSH
    echo "Configuring SSH..."
    mkdir -p /var/run/sshd
    echo 'root:{{ .Values.env.env1.value | default "changeme" }}' | chpasswd || { echo "ERROR: Failed to set root password"; exit 1; }
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin {{ .Values.env.env3.value | default "yes" }}/g' /etc/ssh/sshd_config || { echo "ERROR: Failed to configure PermitRootLogin"; exit 1; }

    # 清理旧 SSH 配置并添加新配置
    echo "Applying additional SSH configuration..."
    {{- range $key, $value := .Values.advanced.sshConfig }}
    sed -i '/^{{ $key }}/d' /etc/ssh/sshd_config
    echo "{{ $key }} {{ $value }}" >> /etc/ssh/sshd_config || { echo "ERROR: Failed to append SSH config"; exit 1; }
    {{- end }}

    # 启动 SSH 服务
    echo "Starting SSH service..."
    exec /usr/sbin/sshd -D || { echo "ERROR: Failed to start sshd"; exit 1; }
