apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ubuntu-ssh.fullname" . }}
  labels:
    {{- include "ubuntu-ssh.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ubuntu-ssh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ubuntu-ssh.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.global.ubuntuVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["/config/setup.sh"]
          ports:
            - containerPort: {{ .Values.env.env2.value }}
              protocol: TCP
          env:
            - name: {{ .Values.env.env1.name }}
              value: {{ .Values.env.env1.value | quote }}
            - name: {{ .Values.env.env2.name }}
              value: {{ .Values.env.env2.value | quote }}
            - name: {{ .Values.env.env3.name }}
              value: {{ .Values.env.env3.value | quote }}
          volumeMounts:
            - name: ssh-config
              mountPath: /config
      volumes:
        - name: ssh-config
          configMap:
            name: {{ include "ubuntu-ssh.fullname" . }}
