apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ubuntu-ssh.fullname" . }}
  labels:
    {{- include "ubuntu-ssh.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "ubuntu-ssh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ubuntu-ssh.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: ubuntu-ssh
          image: "{{ .Values.image.imageRegistry | default "docker.io" }}/{{ .Values.image.repository | default "ubuntu" }}:{{ .Values.image.tag | default "latest" }}"
          ports:
            - containerPort: 22
              name: ssh
          env:
            {{- if .Values.env }}
            - name: {{ .Values.env.env1.name | default "ENV1" }}
              value: {{ .Values.env.env1.value | default "default_value1" | quote }}
            - name: {{ .Values.env.env2.name | default "ENV2" }}
              value: {{ .Values.env.env2.value | default "default_value2" | quote }}
            {{- end }}
          command:
            - /bin/bash
            - -c
            - |
              set -e
              # 替换为国内源
              sed -i 's@http://archive.ubuntu.com/@http://mirrors.aliyun.com/@g' /etc/apt/sources.list && \
              apt-get update && \
              apt-get install -y --no-install-recommends \
                vim \
                net-tools \
                curl \
                wget \
                iputils-ping \
                git \
                nano \
                openssh-server && \
              echo "root:yunna" | chpasswd && \
              sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
              sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
              mkdir -p /var/run/sshd && \
              /usr/sbin/sshd -D
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - |
                    echo "SSH server and essential tools installed."
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "ubuntu-ssh.fullname" . }}-pvc
