apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ubuntu-ssh.fullname" . }}
  labels:
    {{- include "ubuntu-ssh.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ubuntu-ssh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ubuntu-ssh.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: init-ssh-tools
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /bin/bash
            - -c
            - |
              echo "Initializing container with essential tools and SSH setup." && \
              sed -i 's@http://archive.ubuntu.com/@http://mirrors.aliyun.com/@g' /etc/apt/sources.list && \
              apt-get update && \
              apt-get install -y \
                vim \
                net-tools \
                curl \
                wget \
                iputils-ping \
                git \
                nano \
                openssh-server && \
              mkdir -p /run/sshd
      containers:
        - name: ubuntu-ssh
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 22
          env:
            - name: {{ .Values.env.env1.name }}
              value: {{ .Values.env.env1.value | quote }}
            - name: {{ .Values.env.env2.name }}
              value: {{ .Values.env.env2.value | quote }}
          command:
            - /usr/sbin/sshd
            - -D
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - |
                    echo "Container started. SSH server and essential tools are ready."
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "ubuntu-ssh.fullname" . }}-pvc
