apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ubuntu-ssh.fullname" . }}-bandwidth-limit
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ubuntu-ssh.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ubuntu-ssh.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 22
      # 配置带宽限制 (需使用支持的插件，如 Calico)
      limits:
        bandwidth: "{{ .Values.network.egressLimit | default "1Mbps" }}"
