apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "code-server-ssr.fullname" . }}-config
  labels:
    {{- include "code-server-ssr.labels" . | nindent 4 }}
data:
  config.yaml: |
    bind-addr: 0.0.0.0:8080
    auth: none
    {{- if .Values.tls.enabled }}
    cert: /root/.config/code-server/certificates/code-server.crt
    cert-key: /root/.config/code-server/certificates/code-server.key
    {{- end }}