apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "code-server-ssr.fullname" . }}
  labels:
    {{- include "code-server-ssr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "code-server-ssr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "code-server-ssr.labels" . | nindent 8 }}
        {{- include "code-server-ssr.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      initContainers:
        - name: init-permissions
          image: busybox
          command: ['sh', '-c', 'mkdir -p /root/.local/share/code-server /root/.config/code-server && chmod -R 777 /root/.local/share/code-server /root/.config/code-server']
          volumeMounts:
            {{- range .Values.persistence.mountPaths }}
            - name: {{ include "code-server-ssr.name" $ }}-{{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      containers:
        - name: {{ include "code-server-ssr.name" . }}
          image: "{{ .Values.image.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          ports:
            {{- range .Values.services }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          env:
            {{- if kindIs "array" .Values.env }}
            {{- range .Values.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
            {{- else if kindIs "map" .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: "{{ $value.name }}"
              value: "{{ $value.value }}"
            {{- end }}
            {{- end }}
            - name: SHELL
              value: /bin/bash
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range .Values.persistence.mountPaths }}
            - name: {{ include "code-server-ssr.name" $ }}-{{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.persistence.mountPaths }}
        - name: {{ include "code-server-ssr.name" $ }}-{{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "code-server-ssr.fullname" $ }}-{{ .name }}-pvc
        {{- end }}