apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-server-ssr.fullname" . }}
  labels:
    {{- include "code-server-ssr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range .Values.services }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "code-server-ssr.selectorLabels" . | nindent 4 }}