replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: cm2network/cs2
  tag: latest
  pullPolicy: IfNotPresent
services:
  - name: game
    port: 27015
    targetPort: "27015"
    protocol: UDP
  - name: rcon
    port: 27015
    targetPort: "27015"
    protocol: TCP
resources:
  limits:
    cpu: 4000m
    memory: 4096Mi
  requests:
    cpu: 2000m
    memory: 2048Mi
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
env:
  env1:
    name: SRCDS_TOKEN
    value: ""
  env2:
    name: SRCDS_PW
    value: ""
  env3:
    name: SRCDS_RCONPW
    value: ""
