apiVersion: v2
name: adminer
description: 轻量级的数据库管理工具
version: 1.0.0
appVersion: "latest"
home: https://www.adminer.org/
sources:
  - https://github.com/dockette/adminer
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: database
  yunna.net/category-zh: 数据库
keywords:
  - 数据库管理
  - MySQL
  - PostgreSQL
  - 自托管
icon: https://assets.yunna.net/i/2024/12/21/114apom.png
