replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: thmhoag/arkserver
  tag: latest
  pullPolicy: IfNotPresent
services:
  - name: game
    port: 7777
    targetPort: "7777"
    protocol: UDP
  - name: query
    port: 27015
    targetPort: "27015"
    protocol: UDP
  - name: rcon
    port: 27020
    targetPort: "27020"
    protocol: TCP
resources:
  limits:
    cpu: 4000m
    memory: 8192Mi
  requests:
    cpu: 2000m
    memory: 4096Mi
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
env:
  env1:
    name: SERVERMAP
    value: TheIsland
  env2:
    name: SERVERNAME
    value: ARK Server
  env3:
    name: SERVERPASSWORD
    value: ""
  env4:
    name: ADMINPASSWORD
    value: ""
