apiVersion: v2
name: mosquitto
description: Eclipse Mosquitto 是一个开源的消息代理，实现了 MQTT 协议版本 5.0、3.1.1 和 3.1。非常适合物联网场景下的消息传递。
version: 1.0.0
appVersion: 2.0.18
home: https://mosquitto.org/
sources:
  - https://github.com/eclipse/mosquitto
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: middleware
  yunna.net/category-zh: 中间件
keywords:
  - mqtt
  - broker
  - iot
  - messaging
icon: https://assets.yunna.net/i/2024/12/22/voh6ni.png
