apiVersion: v2
name: mosquitto
description: 开源的MQTT消息代理服务器，专注于为物联网设备提供轻量级的发布/订阅消息传输
version: 1.0.0
appVersion: latest
home: https://mosquitto.org/
sources:
  - https://github.com/eclipse/mosquitto
maintainers:
  - name: Eclipse Foundation
    email: info@mosquitto.org
annotations:
  yunna.net/category: middleware
  yunna.net/category-zh: 中间件
keywords:
  - mqtt
  - broker
  - iot
  - Self-hosted
icon: https://assets.yunna.net/i/2024/12/27/54pibu.png
