replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: eclipse-mosquitto
  tag: 2.0.18
  pullPolicy: IfNotPresent
services:
  - name: mqtt
    port: 1883
    targetPort: "1883"
    protocol: TCP
  - name: websocket
    port: 9001
    targetPort: "9001"
    protocol: TCP
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
  mountPath: /app/data
env:
  env1:
    name: MOSQUITTO_USERNAME
    value: admin
  env2:
    name: MOSQUITTO_PASSWORD
    value: password123
