apiVersion: v2
name: netshoot
description: 功能强大的网络诊断和调试工具箱，包含各种网络工具
version: 0.1.0
appVersion: latest
home: https://github.com/nicolaka/netshoot
sources:
  - https://github.com/nicolaka/netshoot
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: Network Tools
  yunna.net/category-zh: 网络工具
keywords:
  - network
  - diagnostics
  - troubleshooting
  - debug
icon: https://assets.yunna.net/i/2024/12/15/ci9paz.png
