apiVersion: v2
name: frps
description: FRPS (快速反向代理服务器也可以用来联机游戏)，用于实现内网穿透和本地服务的公开。
version: 0.61.1
appVersion: v0.61.1
home: https://github.com/fatedier/frp
sources:
  - https://github.com/fatedier/frp
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: networking
  yunna.net/category-zh: 网络
keywords:
  - 反向代理
  - frp
  - 内网穿透
  - 隧道
icon: https://assets.yunna.net/i/2024/12/26/126fbbq.jpg
