replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: fatedier/frps
  tag: v0.61.1
  pullPolicy: IfNotPresent
services:
  - name: dashboard
    port: 7500
    targetPort: "7500"
    protocol: TCP
    description: FRPS 仪表盘服务，用于监控和管理。
  - name: proxy
    port: 7000
    targetPort: "7000"
    protocol: TCP
    description: FRPS 代理服务，接受客户端连接。
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
env:
  env1:
    name: FRPS_DASHBOARD_PORT
    value: "7500"
  env2:
    name: FRPS_TOKEN
    value: 随便你填个你记得住的密码
  env3:
    name: FRPS_BIND_PORT
    value: "7000"
volumes:
  - name: config
    path: /frp
    comment: 挂载 frps.ini 配置文件的路径。
