replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: nidexiong/code-server-ssr
  tag: latest
  pullPolicy: Always
services:
  - name: http
    port: 8080
    targetPort: "8080"
    protocol: TCP
resources:
  limits:
    cpu: 1000m
    memory: 2000Mi
  requests:
    cpu: 500m
    memory: 512Mi
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: local
env:
  env1:
    name: PASSWORD
    value: changeme

tls:
  enabled: true
  secretName: code-server-tls
  # 这是一个自签名证书和私钥（不要在生产环境使用）
  crt: |
    -----BEGIN CERTIFICATE-----
    MIIDazCCAlOgAwIBAgIUBGN+tqDWa1Ct8guQs7WK5CX7tWAwDQYJKoZIhvcNAQEL
    BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNTAxMTEwMzI3MTZaFw0yNjAx
    MTAwMzI3MTZaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
    HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQDRXDcLQwxD9jOWNJBqINVNUuViU14yH3FyCY79AhX+
    xKLB0w/H5Ob1n3jaNZFhWf9wBWkGPcQDvVV5L9vmiH/EfZ1qJtIqL7CeNvABX/1X
    0ZfP0kJO9JH9k/9Ee8J+PITxvJ/0jpPtPfUCd6iuTsoM1vX4GzaQsbCW4AX1hX3n
    BQu0YtBCjOIMl//KmYbM5Oi8eaH5vR/FbJ1OAvN7CmZxZf/PZaYmGc2NJLjKwYHF
    n6z9ZZTTLaHClwzn8X0vO9MFAf+4jIXTBQkZsKLEQx7tUKXiQbIZN1uT9TtFevl7
    RcHIyYGQGaIL1nnmw3rUoTUn2eVB0EEXSCu6qTAHAgMBAAGjUzBRMB0GA1UdDgQW
    BBTHp+yXjFyZWQ6ZOJ4TY0BVPpFGMDAfBgNVHSMEGDAWgBTHp+yXjFyZWQ6ZOJ4T
    Y0BVPpFGMDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQB3EzL0
    0RkKJ3BHjwpP1O22zG6w1LBQTCfkE6p6GsF7n6AlB5W2jnE+0hZ5ASsGqwGLJzGp
    1fsF0a8nLuC1C7x4I7wFJPQHK6M6UhEstzX6+IlS6zXn5+dHBXvK5CNzEv5r7GDJ
    eNc/1yJ2N1WcNmz2ZdZNX/t5Z+0VqoEiZ5VGJVsZdX4xSeXAB6a5Z2u0sF5t5Wq7
    4MjLwJ5QlZLgvK3QY5BVp7UGzR1j5XRs1nvSXJ8CUx5Ym0p9Ap8WSmD+kJgZjuZp
    1YG9vcBJJ6h8u4aIzVG9e7Jg8Ry7wSB8IkEkC5VXZH2aEUFY0cKqXDjkHEXL7SbB
    QdI8mKgOvJT8kvxg
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDRXDcLQwxD9jOW
    NJBqINVNUuViU14yH3FyCY79AhX+xKLB0w/H5Ob1n3jaNZFhWf9wBWkGPcQDvVV5
    L9vmiH/EfZ1qJtIqL7CeNvABX/1X0ZfP0kJO9JH9k/9Ee8J+PITxvJ/0jpPtPfUC
    d6iuTsoM1vX4GzaQsbCW4AX1hX3nBQu0YtBCjOIMl//KmYbM5Oi8eaH5vR/FbJ1O
    AvN7CmZxZf/PZaYmGc2NJLjKwYHFn6z9ZZTTLaHClwzn8X0vO9MFAf+4jIXTBQkZ
    sKLEQx7tUKXiQbIZN1uT9TtFevl7RcHIyYGQGaIL1nnmw3rUoTUn2eVB0EEXSCu6
    qTAHAgMBAAECggEBAJVK9CyM1wPd9DTtFDYkR9heJnItsNGrEZo+rM+Y5jG6rFC9
    GnI7Uy6L1oQyB1TJ+igWPW5wKhN+pz1GwXmLiJ0kqYBxDlF5q1cxKK1U4V8FrZX8
    0KUc6LV5Q1Y6P6jCuvU0Qa5UttN5BPCU6S8qKL6T8PdPEQL8SYOgQ2ZZG+Air4+/
    cE0qF2B9cw7eJmr7x1ZN3UFTCjRJmQX6Rw6M2zMD2S8UR8Sz8Ut/4bXDpN4UnUk7
    HcJwz9hrIp8xKvnQNvShPwZ6eVE1JhcbZW0rWmzGeyO1J5he1fjT9Q674xNu+KCq
    NUoDsW0ZYLvXSEwdXkBQnQZCKqF4JtD/ZVV4vgECgYEA8m+HS2jYbD0RVH4nWBd7
    7pLJgN2UZePR4A6DsQ+/THtW1MFEhH7NJ8GNQc8ebM0Jk6hkWvd1cclzuF6F9pkv
    5z5pqGxB4D73k1Lv0mzQXkZcjGMtP5R5hZ3RKyPXoA4m0dp4PbUjXHuF6C2HoEWC
    b8qL8FhFJ3ij6krlY2YijsECgYEA3O3mO6lhGDG5DCON/f9i7KN6Ci5ZoBHPXSLf
    p+5lL0jPxc6QZlX4xZoFXzm1NQ5U9WyZQRDKz5dK5ElRHVv3RlQ4ufkb1v3JXeGQ
    j5uhBEvsJZF3OjXw7GZIZaBCkJqpHo8kiXcD9B7D3U6Z2P4SUYjbFHSIEpPuUNOx
    cC2nNwcCgYEA2FtP3XNp8jhTF9rZ1vGABwVeNFJAZ4NEZwvL2ArGKROBvIHCFGKp
    oRm3hOyPEVB5rkHZnADEFu9JigOCmJc6E0z2aQqNxvIHu7Mhn7rVX7vVIKAQ2P2W
    0P4ssvtS1AoC/S9zYOYBcF3qDwuQRHjM+jz73u2HOjHrx6QqTy57gEECgYEAo4yw
    +5dOYeMZZ01t6pRvmVrI8ZLDSXpbQOe6E8ZqX6uE9AO5EI8sH+n0JZjVpyj9iqpu
    7FoX1u7F97QNHEpBvwz4bxy6TaLD1V/YglE1rAmz6cPZHhK4vaPOPVG2k9h0DJVH
    LTh+6oCuZ+iu9i6buHCFWOH0y2JH51HJCNi0yKMCgYAiAZKLfM2c8FvArDfdvIcO
    c3ZN6QDlJHjHtmwdO8cm1X1r3Q8zFmZl5TyfaY3FCc1uB0zbGRZ5W0DXJRn8HiFc
    T0UpUqM39S7FJ11HDg35LlfCrXq0J4IHYzL85ElwOVBAsh0P/BpMJxSvbVwvJTSx
    UdyVD00Y1p0v4mZ6kZz9Yw==
    -----END PRIVATE KEY-----
