apiVersion: v2
name: flarum
description: 现代化的轻量级开源论坛系统
version: 0.1.0
appVersion: latest
home: https://flarum.org/
sources:
  - https://github.com/flarum/flarum
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: Forum
  yunna.net/category-zh: 论坛
keywords:
  - forum
  - discussion
  - community
icon: https://assets.yunna.net/i/2024/12/21/qslu0s.jpeg
