replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: mondedie/flarum
  tag: latest
  pullPolicy: IfNotPresent
services:
  - name: http
    port: 80
    targetPort: "8000"
    protocol: TCP
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
  mountPath: /app/data
env:
  # 论坛配置
  forum_title:
    name: FLARUM_FORUM_TITLE
    value: "我的社区"
  admin_user:
    name: FLARUM_ADMIN_USER
    value: "admin"
  admin_password:
    name: FLARUM_ADMIN_PASSWORD
    value: "password"
  base_url:
    name: FLARUM_BASE_URL
    value: "http://localhost"
