apiVersion: v2
name: valheim-server
description: 北欧神话风格生存游戏英灵神殿的多人联机服务器，支持最多10人同时在线
version: 1.0.0
appVersion: latest
home: https://github.com/lloesche/valheim-server-docker
sources:
  - https://github.com/lloesche/valheim-server-docker
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: game-server
  yunna.net/category-zh: 游戏服务器
keywords:
  - Game Server
  - Steam
  - Valheim
icon: https://assets.yunna.net/i/2024/12/30/wbz65.png
