apiVersion: v2
name: left4dead2-server
description: 求生之路2多人联机服务器，支持战役、对抗、清道夫等多种游戏模式
version: 1.0.0
appVersion: latest
home: https://github.com/CM2Walki/steamcmd
sources:
  - https://github.com/CM2Walki/steamcmd
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: game-server
  yunna.net/category-zh: 游戏服务器
keywords:
  - Game Server
  - Steam
  - L4D2
icon: https://assets.yunna.net/i/2024/12/30/v4aov.png
