apiVersion: v2
name: dst-server
description: 饥荒联机版独立服务器
version: 1.0.0
appVersion: latest
home: https://www.klei.com/games/dont-starve-together
sources:
  - https://www.klei.com/games/dont-starve-together
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: game
  yunna.net/category-zh: 游戏
keywords:
  - game
  - Self-hosted
icon: https://assets.yunna.net/i/2024/12/26/126zffm.png
