replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: snowdreamtech/dst-server
  tag: latest
  pullPolicy: IfNotPresent
services:
  - name: game
    port: 10999
    targetPort: "10999"
    protocol: UDP
resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 1024Mi
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
env:
  env1:
    name: CLUSTER_NAME
    value: 我的饥荒服务器
  env2:
    name: CLUSTER_DESCRIPTION
    value: 这是一个饥荒服务器
  env3:
    name: CLUSTER_PASSWORD
    value: ""
  env4:
    name: CLUSTER_INTENTION
    value: cooperative
  env5:
    name: GAMEMODE
    value: survival
  env6:
    name: MAX_PLAYERS
    value: "6"
  env7:
    name: PVP
    value: "false"
  env8:
    name: PAUSE_WHEN_EMPTY
    value: "true"
