apiVersion: v2
name: filecodebox
description: 文件分享工具
version: 0.1.0
appVersion: "latest"
home: https://github.com/file-code-box/filecodebox
sources:
  - https://github.com/file-code-box/filecodebox
maintainers:
  - name: niehaoran
    email: niehaoran@yunna.net
annotations:
  yunna.net/category: tools
  yunna.net/category-zh: 实用工具
keywords:
  - file-sharing
icon: https://assets.yunna.net/i/2024/12/22/3vnbpm.png
