replicaCount: 1
image:
  imageRegistry: registry-2.yunna.net
  repository: liesauer/filecodebox
  tag: latest
  pullPolicy: IfNotPresent
services:
  - name: http
    port: 3000
    targetPort: "3000"
    protocol: TCP
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: local
  mountPath: /app/data
env:
  env1:
    name: APP_KEY
    value: ""
  env2:
    name: ADMIN_USERNAME
    value: ""
  env3:
    name: ADMIN_PASSWORD
    value: ""
