apiVersion: extensions.kubesphere.io/v1alpha1
kind: APIService
metadata:
  name: v1alpha1.sidecar.yunna.net
  labels:
    app.kubernetes.io/managed-by: Helm
    kubesphere.io/extension-ref: {{ .Release.Name }}
    {{- include "sidecar-plugin.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  group: sidecar.yunna.net
  version: v1alpha1
  url: 'http://{{ include "sidecar-plugin.fullname" . }}.{{ .Release.Namespace }}.svc:8080'